//
//  ClipboardManager.swift
//  FastGrep 快摘
//
//  Created by Drinking on 10/24/25.
//  Copyright © 2024 Drinking. All rights reserved.
//

import Foundation
import AppKit
import SwiftUI

// 剪贴板项目类型
enum ClipboardItemType: String, CaseIterable, Codable {
    case text = "text"
    case image = "image"
    case file = "file"
    case url = "url"
    case color = "color"
    
    var displayName: String {
        switch self {
        case .text: return "文本"
        case .image: return "图片"
        case .file: return "文件"
        case .url: return "链接"
        case .color: return "颜色"
        }
    }
    
    var systemIcon: String {
        switch self {
        case .text: return "doc.text"
        case .image: return "photo"
        case .file: return "doc"
        case .url: return "link"
        case .color: return "paintpalette"
        }
    }
}

// 剪贴板历史项目
struct ClipboardItem: Identifiable, Codable, Hashable {
    var id: UUID
    var content: String
    var type: ClipboardItemType
    var timestamp: Date
    var source: String? // 来源应用
    var preview: String // 预览文本
    var size: Int // 内容大小
    var isFavorite: Bool = false
    var useCount: Int = 0
    var lastUsed: Date?
    
    init(content: String, type: ClipboardItemType, source: String? = nil) {
        self.id = UUID()
        self.content = content
        self.type = type
        self.timestamp = Date()
        self.source = source
        self.size = content.count
        
        // 生成预览文本
        switch type {
        case .text:
            self.preview = content.trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "\n", with: " ")
                .prefix(100) + (content.count > 100 ? "..." : "")
        case .url:
            self.preview = content
        case .file:
            let firstLine = content.components(separatedBy: .newlines).first ?? content
            if firstLine.hasPrefix("file://"), let u = URL(string: firstLine) {
                self.preview = u.lastPathComponent
            } else {
                self.preview = (firstLine as NSString).lastPathComponent
            }
        case .image:
            self.preview = "图片内容"
        case .color:
            self.preview = "颜色: \(content)"
        }
    }
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(content)
        hasher.combine(type)
    }
    
    static func == (lhs: ClipboardItem, rhs: ClipboardItem) -> Bool {
        return lhs.id == rhs.id
    }
}

// 剪贴板管理器
class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()
    
    @Published var history: [ClipboardItem] = []
    @Published var isMonitoring: Bool = false
    
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private let maxHistorySize: Int = 1000
    private let pasteboard = NSPasteboard.general
    
    // 数据库相关
    private let userDefaults = UserDefaults.standard
    private let historyKey = "clipboard_history"
    
    private init() {
        loadHistory()
        setupNotifications()
    }
    
    deinit {
        stopMonitoring()
        NotificationCenter.default.removeObserver(self)
    }
    
    // MARK: - 监控控制
    
    func startMonitoring() {
        guard !isMonitoring else { return }
        
        isMonitoring = true
        lastChangeCount = pasteboard.changeCount
        
        // 每0.5秒检查一次剪贴板变化
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { _ in
            self.checkClipboardChanges()
        }
        
        print("📋 剪贴板监控已启动")
    }
    
    func stopMonitoring() {
        isMonitoring = false
        timer?.invalidate()
        timer = nil
        print("📋 剪贴板监控已停止")
    }
    
    // MARK: - 剪贴板变化检测
    
    private func checkClipboardChanges() {
        let currentChangeCount = pasteboard.changeCount
        
        if currentChangeCount != lastChangeCount {
            lastChangeCount = currentChangeCount
            handleClipboardChange()
        }
    }
    
    private func handleClipboardChange() {
        guard let clipboardContent = getClipboardContent() else { return }
        
        // 避免重复添加相同内容
        if let lastItem = history.first, lastItem.content == clipboardContent.content {
            return
        }
        
        // 添加到历史记录
        addToHistory(clipboardContent)
    }
    
    // MARK: - 剪贴板内容获取
    
    private func getClipboardContent() -> ClipboardItem? {
        let types = pasteboard.types ?? []
        
        // 隐私安全过滤：识别并自动忽略密码管理器（1Password、Bitwarden、MacPass 等）复制的敏感内容
        let sensitiveTypes = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "de.plessmann.macpass"
        ]
        for typeIdentifier in sensitiveTypes {
            if types.contains(NSPasteboard.PasteboardType(typeIdentifier)) {
                return nil
            }
        }
        
        // 获取当前活跃应用
        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName
        
        // 1. 优先检查系统文件类型（如访达中复制的文件或目录）
        if types.contains(.fileURL), let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], !fileURLs.isEmpty {
            let filePaths = fileURLs.map { $0.path }.joined(separator: "\n")
            return ClipboardItem(content: filePaths, type: .file, source: sourceApp)
        }
        
        // 2. 检查文本内容类型
        if types.contains(.string), let string = pasteboard.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            
            // 检查是否为 file:// 链接
            if trimmed.hasPrefix("file://") {
                return ClipboardItem(content: trimmed, type: .file, source: sourceApp)
            }
            
            // 检查是否为标准 http/https 网页链接
            if let url = URL(string: trimmed), let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https" {
                return ClipboardItem(content: trimmed, type: .url, source: sourceApp)
            }
            
            // 检查是否为本地文件路径（单行且以 / 或 ~ 开头）
            if (trimmed.hasPrefix("/") || trimmed.hasPrefix("~")) && !trimmed.contains("\n") && (trimmed.hasPrefix("/Users/") || trimmed.hasPrefix("/Applications/") || trimmed.hasPrefix("/System/") || trimmed.hasPrefix("/Volumes/") || trimmed.contains("/")) {
                return ClipboardItem(content: trimmed, type: .file, source: sourceApp)
            }
            
            // 检查是否为颜色 (hex)
            if trimmed.hasPrefix("#") && (trimmed.count == 7 || trimmed.count == 9) {
                return ClipboardItem(content: trimmed, type: .color, source: sourceApp)
            }
            
            return ClipboardItem(content: trimmed, type: .text, source: sourceApp)
        }
        
        // 3. 检查图片类型
        if types.contains(.tiff), let imageData = pasteboard.data(forType: .tiff) {
            let base64String = imageData.base64EncodedString()
            return ClipboardItem(content: "data:image/tiff;base64,\(base64String)", type: .image, source: sourceApp)
        }
        
        if types.contains(.png), let imageData = pasteboard.data(forType: .png) {
            let base64String = imageData.base64EncodedString()
            return ClipboardItem(content: "data:image/png;base64,\(base64String)", type: .image, source: sourceApp)
        }
        
        return nil
    }
    
    // MARK: - 历史记录管理
    
    func addToHistory(_ item: ClipboardItem) {
        DispatchQueue.main.async {
            // 移除重复项
            self.history.removeAll { $0.content == item.content }
            
            // 添加到开头
            self.history.insert(item, at: 0)
            
            // 限制历史记录大小
            if self.history.count > self.maxHistorySize {
                self.history = Array(self.history.prefix(self.maxHistorySize))
            }
            
            // 保存到本地
            self.saveHistory()
            
            print("📋 新增剪贴板项目: \(item.preview)")
        }
    }
    
    func copyToClipboard(_ item: ClipboardItem) {
        // 更新使用统计
        updateItemUsage(item)
        
        pasteboard.clearContents()
        
        switch item.type {
        case .text, .url, .color:
            pasteboard.setString(item.content, forType: .string)
        case .file:
            let urls = item.content.components(separatedBy: "\n").compactMap { URL(fileURLWithPath: $0) }
            pasteboard.writeObjects(urls as [NSURL])
        case .image:
            if let data = Data(base64Encoded: item.content.replacingOccurrences(of: "data:image/tiff;base64,", with: "").replacingOccurrences(of: "data:image/png;base64,", with: "")) {
                pasteboard.setData(data, forType: item.content.contains("png") ? .png : .tiff)
            }
        }
        
        print("📋 复制到剪贴板: \(item.preview)")
    }
    
    private func updateItemUsage(_ item: ClipboardItem) {
        if let index = history.firstIndex(where: { $0.id == item.id }) {
            history[index].useCount += 1
            history[index].lastUsed = Date()
            saveHistory()
        }
    }
    
    func toggleFavorite(_ item: ClipboardItem) {
        if let index = history.firstIndex(where: { $0.id == item.id }) {
            history[index].isFavorite.toggle()
            saveHistory()
        }
    }
    
    func deleteItem(_ item: ClipboardItem) {
        history.removeAll { $0.id == item.id }
        saveHistory()
    }
    
    func clearHistory() {
        history.removeAll()
        saveHistory()
    }
    
    // MARK: - 搜索功能
    
    func searchHistory(query: String) -> [ClipboardItem] {
        guard !query.isEmpty else { return history }
        
        let lowercaseQuery = query.lowercased()
        
        return history.filter { item in
            // 搜索内容
            if item.content.lowercased().contains(lowercaseQuery) {
                return true
            }
            
            // 搜索预览文本
            if item.preview.lowercased().contains(lowercaseQuery) {
                return true
            }
            
            // 搜索来源应用
            if let source = item.source, source.lowercased().contains(lowercaseQuery) {
                return true
            }
            
            // 搜索类型
            if item.type.displayName.contains(query) {
                return true
            }
            
            return false
        }
    }
    
    func getHistoryByType(_ type: ClipboardItemType) -> [ClipboardItem] {
        return history.filter { $0.type == type }
    }
    
    func getFavorites() -> [ClipboardItem] {
        return history.filter { $0.isFavorite }
    }
    
    func getFrequentlyUsed(limit: Int = 10) -> [ClipboardItem] {
        return history.sorted { $0.useCount > $1.useCount }.prefix(limit).map { $0 }
    }
    
    // MARK: - 数据持久化
    
    private func saveHistory() {
        do {
            // 只保存非图片类型的历史记录，防止 UserDefaults 超限
            let filteredHistory = history.filter { $0.type != .image }
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            let data = try encoder.encode(filteredHistory)
            userDefaults.set(data, forKey: historyKey)
        } catch {
            print("❌ 保存剪贴板历史失败: \(error)")
        }
    }
    
    private func loadHistory() {
        guard let data = userDefaults.data(forKey: historyKey) else { return }
        
        do {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            history = try decoder.decode([ClipboardItem].self, from: data)
            print("📋 已加载 \(history.count) 个剪贴板历史项目")
        } catch {
            print("❌ 加载剪贴板历史失败: \(error)")
            history = []
        }
    }
    
    // MARK: - 通知处理
    
    private func setupNotifications() {
        // 应用激活时开始监控
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(applicationDidBecomeActive),
            name: NSApplication.didBecomeActiveNotification,
            object: nil
        )
        
        // 应用进入后台时停止监控（可选，节省资源）
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(applicationWillResignActive),
            name: NSApplication.willResignActiveNotification,
            object: nil
        )
    }
    
    @objc private func applicationDidBecomeActive() {
        if !isMonitoring {
            startMonitoring()
        }
    }
    
    @objc private func applicationWillResignActive() {
        // 可以选择在这里停止监控，但通常我们希望继续监控
        // stopMonitoring()
    }
    
    // MARK: - 统计信息
    
    func getStatistics() -> ClipboardStatistics {
        let totalItems = history.count
        let totalSize = history.reduce(0) { $0 + $1.size }
        let typeDistribution = Dictionary(grouping: history, by: { $0.type })
            .mapValues { $0.count }
        
        let today = Calendar.current.startOfDay(for: Date())
        let todayItems = history.filter { Calendar.current.startOfDay(for: $0.timestamp) == today }
        
        return ClipboardStatistics(
            totalItems: totalItems,
            totalSize: totalSize,
            typeDistribution: typeDistribution,
            todayItems: todayItems.count,
            favoriteItems: getFavorites().count,
            mostUsedType: typeDistribution.max(by: { $0.value < $1.value })?.key ?? .text
        )
    }
}

// 统计数据结构
struct ClipboardStatistics {
    let totalItems: Int
    let totalSize: Int
    let typeDistribution: [ClipboardItemType: Int]
    let todayItems: Int
    let favoriteItems: Int
    let mostUsedType: ClipboardItemType
    
    var averageSize: Double {
        return totalItems > 0 ? Double(totalSize) / Double(totalItems) : 0
    }
    
    var formattedTotalSize: String {
        return ByteCountFormatter.string(fromByteCount: Int64(totalSize), countStyle: .memory)
    }
}